interface=__LAN_INTERFACE__
bind-dynamic
listen-address=172.20.10.1
dhcp-range=172.20.10.50,172.20.10.200,255.255.255.0,24h
dhcp-option=3,172.20.10.1
dhcp-option=6,172.20.10.1
resolv-file=/run/systemd/resolve/resolv.conf
server=8.8.8.8
server=8.8.4.4
address=/vigilant.local/172.20.10.1
address=/mitm.it/172.20.10.1
log-queries
log-facility=/var/log/dnsmasq.log
domain-needed
bogus-priv
